/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.dundalek.notcurses.swig;

public final class ncalign_e {
  public final static ncalign_e NCALIGN_UNALIGNED = new ncalign_e("NCALIGN_UNALIGNED");
  public final static ncalign_e NCALIGN_LEFT = new ncalign_e("NCALIGN_LEFT");
  public final static ncalign_e NCALIGN_CENTER = new ncalign_e("NCALIGN_CENTER");
  public final static ncalign_e NCALIGN_RIGHT = new ncalign_e("NCALIGN_RIGHT");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ncalign_e swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ncalign_e.class + " with value " + swigValue);
  }

  private ncalign_e(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ncalign_e(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ncalign_e(String swigName, ncalign_e swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ncalign_e[] swigValues = { NCALIGN_UNALIGNED, NCALIGN_LEFT, NCALIGN_CENTER, NCALIGN_RIGHT };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

