/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.dundalek.notcurses.swig;

public class nccell {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected nccell(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(nccell obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NCJNI.delete_nccell(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setGcluster(long value) {
    NCJNI.nccell_gcluster_set(swigCPtr, this, value);
  }

  public long getGcluster() {
    return NCJNI.nccell_gcluster_get(swigCPtr, this);
  }

  public void setGcluster_backstop(short value) {
    NCJNI.nccell_gcluster_backstop_set(swigCPtr, this, value);
  }

  public short getGcluster_backstop() {
    return NCJNI.nccell_gcluster_backstop_get(swigCPtr, this);
  }

  public void setWidth(short value) {
    NCJNI.nccell_width_set(swigCPtr, this, value);
  }

  public short getWidth() {
    return NCJNI.nccell_width_get(swigCPtr, this);
  }

  public void setStylemask(int value) {
    NCJNI.nccell_stylemask_set(swigCPtr, this, value);
  }

  public int getStylemask() {
    return NCJNI.nccell_stylemask_get(swigCPtr, this);
  }

  public void setChannels(long value) {
    NCJNI.nccell_channels_set(swigCPtr, this, value);
  }

  public long getChannels() {
    return NCJNI.nccell_channels_get(swigCPtr, this);
  }

  public nccell() {
    this(NCJNI.new_nccell(), true);
  }

}
