/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.dundalek.notcurses.swig;

public class ncfdplane_options {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ncfdplane_options(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ncfdplane_options obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NCJNI.delete_ncfdplane_options(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCurry(SWIGTYPE_p_void value) {
    NCJNI.ncfdplane_options_curry_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getCurry() {
    long cPtr = NCJNI.ncfdplane_options_curry_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setFollow(boolean value) {
    NCJNI.ncfdplane_options_follow_set(swigCPtr, this, value);
  }

  public boolean getFollow() {
    return NCJNI.ncfdplane_options_follow_get(swigCPtr, this);
  }

  public void setFlags(long value) {
    NCJNI.ncfdplane_options_flags_set(swigCPtr, this, value);
  }

  public long getFlags() {
    return NCJNI.ncfdplane_options_flags_get(swigCPtr, this);
  }

  public ncfdplane_options() {
    this(NCJNI.new_ncfdplane_options(), true);
  }

}
