/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.dundalek.notcurses.swig;

public final class ncintype_e {
  public final static ncintype_e NCTYPE_UNKNOWN = new ncintype_e("NCTYPE_UNKNOWN");
  public final static ncintype_e NCTYPE_PRESS = new ncintype_e("NCTYPE_PRESS");
  public final static ncintype_e NCTYPE_REPEAT = new ncintype_e("NCTYPE_REPEAT");
  public final static ncintype_e NCTYPE_RELEASE = new ncintype_e("NCTYPE_RELEASE");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ncintype_e swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ncintype_e.class + " with value " + swigValue);
  }

  private ncintype_e(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ncintype_e(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ncintype_e(String swigName, ncintype_e swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ncintype_e[] swigValues = { NCTYPE_UNKNOWN, NCTYPE_PRESS, NCTYPE_REPEAT, NCTYPE_RELEASE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

