/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.dundalek.notcurses.swig;

public class ncinput {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ncinput(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ncinput obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NCJNI.delete_ncinput(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setId(long value) {
    NCJNI.ncinput_id_set(swigCPtr, this, value);
  }

  public long getId() {
    return NCJNI.ncinput_id_get(swigCPtr, this);
  }

  public void setY(int value) {
    NCJNI.ncinput_y_set(swigCPtr, this, value);
  }

  public int getY() {
    return NCJNI.ncinput_y_get(swigCPtr, this);
  }

  public void setX(int value) {
    NCJNI.ncinput_x_set(swigCPtr, this, value);
  }

  public int getX() {
    return NCJNI.ncinput_x_get(swigCPtr, this);
  }

  public void setUtf8(String value) {
    NCJNI.ncinput_utf8_set(swigCPtr, this, value);
  }

  public String getUtf8() {
    return NCJNI.ncinput_utf8_get(swigCPtr, this);
  }

  public void setAlt(boolean value) {
    NCJNI.ncinput_alt_set(swigCPtr, this, value);
  }

  public boolean getAlt() {
    return NCJNI.ncinput_alt_get(swigCPtr, this);
  }

  public void setShift(boolean value) {
    NCJNI.ncinput_shift_set(swigCPtr, this, value);
  }

  public boolean getShift() {
    return NCJNI.ncinput_shift_get(swigCPtr, this);
  }

  public void setCtrl(boolean value) {
    NCJNI.ncinput_ctrl_set(swigCPtr, this, value);
  }

  public boolean getCtrl() {
    return NCJNI.ncinput_ctrl_get(swigCPtr, this);
  }

  public void setEvtype(ncintype_e value) {
    NCJNI.ncinput_evtype_set(swigCPtr, this, value.swigValue());
  }

  public ncintype_e getEvtype() {
    return ncintype_e.swigToEnum(NCJNI.ncinput_evtype_get(swigCPtr, this));
  }

  public void setModifiers(long value) {
    NCJNI.ncinput_modifiers_set(swigCPtr, this, value);
  }

  public long getModifiers() {
    return NCJNI.ncinput_modifiers_get(swigCPtr, this);
  }

  public void setYpx(int value) {
    NCJNI.ncinput_ypx_set(swigCPtr, this, value);
  }

  public int getYpx() {
    return NCJNI.ncinput_ypx_get(swigCPtr, this);
  }

  public void setXpx(int value) {
    NCJNI.ncinput_xpx_set(swigCPtr, this, value);
  }

  public int getXpx() {
    return NCJNI.ncinput_xpx_get(swigCPtr, this);
  }

  public ncinput() {
    this(NCJNI.new_ncinput(), true);
  }

}
