/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.dundalek.notcurses.swig;

public final class ncloglevel_e {
  public final static ncloglevel_e NCLOGLEVEL_SILENT = new ncloglevel_e("NCLOGLEVEL_SILENT", -1);
  public final static ncloglevel_e NCLOGLEVEL_PANIC = new ncloglevel_e("NCLOGLEVEL_PANIC", 0);
  public final static ncloglevel_e NCLOGLEVEL_FATAL = new ncloglevel_e("NCLOGLEVEL_FATAL", 1);
  public final static ncloglevel_e NCLOGLEVEL_ERROR = new ncloglevel_e("NCLOGLEVEL_ERROR", 2);
  public final static ncloglevel_e NCLOGLEVEL_WARNING = new ncloglevel_e("NCLOGLEVEL_WARNING", 3);
  public final static ncloglevel_e NCLOGLEVEL_INFO = new ncloglevel_e("NCLOGLEVEL_INFO", 4);
  public final static ncloglevel_e NCLOGLEVEL_VERBOSE = new ncloglevel_e("NCLOGLEVEL_VERBOSE", 5);
  public final static ncloglevel_e NCLOGLEVEL_DEBUG = new ncloglevel_e("NCLOGLEVEL_DEBUG", 6);
  public final static ncloglevel_e NCLOGLEVEL_TRACE = new ncloglevel_e("NCLOGLEVEL_TRACE", 7);

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ncloglevel_e swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ncloglevel_e.class + " with value " + swigValue);
  }

  private ncloglevel_e(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ncloglevel_e(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ncloglevel_e(String swigName, ncloglevel_e swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ncloglevel_e[] swigValues = { NCLOGLEVEL_SILENT, NCLOGLEVEL_PANIC, NCLOGLEVEL_FATAL, NCLOGLEVEL_ERROR, NCLOGLEVEL_WARNING, NCLOGLEVEL_INFO, NCLOGLEVEL_VERBOSE, NCLOGLEVEL_DEBUG, NCLOGLEVEL_TRACE };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

