/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.dundalek.notcurses.swig;

public class ncmenu_item {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ncmenu_item(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ncmenu_item obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NCJNI.delete_ncmenu_item(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setDesc(String value) {
    NCJNI.ncmenu_item_desc_set(swigCPtr, this, value);
  }

  public String getDesc() {
    return NCJNI.ncmenu_item_desc_get(swigCPtr, this);
  }

  public void setShortcut(ncinput value) {
    NCJNI.ncmenu_item_shortcut_set(swigCPtr, this, ncinput.getCPtr(value), value);
  }

  public ncinput getShortcut() {
    long cPtr = NCJNI.ncmenu_item_shortcut_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ncinput(cPtr, false);
  }

  public ncmenu_item() {
    this(NCJNI.new_ncmenu_item(), true);
  }

}
