/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.dundalek.notcurses.swig;

public class ncmenu_options {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ncmenu_options(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ncmenu_options obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NCJNI.delete_ncmenu_options(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSections(ncmenu_section value) {
    NCJNI.ncmenu_options_sections_set(swigCPtr, this, ncmenu_section.getCPtr(value), value);
  }

  public ncmenu_section getSections() {
    long cPtr = NCJNI.ncmenu_options_sections_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ncmenu_section(cPtr, false);
  }

  public void setSectioncount(int value) {
    NCJNI.ncmenu_options_sectioncount_set(swigCPtr, this, value);
  }

  public int getSectioncount() {
    return NCJNI.ncmenu_options_sectioncount_get(swigCPtr, this);
  }

  public void setHeaderchannels(long value) {
    NCJNI.ncmenu_options_headerchannels_set(swigCPtr, this, value);
  }

  public long getHeaderchannels() {
    return NCJNI.ncmenu_options_headerchannels_get(swigCPtr, this);
  }

  public void setSectionchannels(long value) {
    NCJNI.ncmenu_options_sectionchannels_set(swigCPtr, this, value);
  }

  public long getSectionchannels() {
    return NCJNI.ncmenu_options_sectionchannels_get(swigCPtr, this);
  }

  public void setFlags(long value) {
    NCJNI.ncmenu_options_flags_set(swigCPtr, this, value);
  }

  public long getFlags() {
    return NCJNI.ncmenu_options_flags_get(swigCPtr, this);
  }

  public ncmenu_options() {
    this(NCJNI.new_ncmenu_options(), true);
  }

}
