/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.dundalek.notcurses.swig;

public final class ncpixelimpl_e {
  public final static ncpixelimpl_e NCPIXEL_NONE = new ncpixelimpl_e("NCPIXEL_NONE", 0);
  public final static ncpixelimpl_e NCPIXEL_SIXEL = new ncpixelimpl_e("NCPIXEL_SIXEL");
  public final static ncpixelimpl_e NCPIXEL_LINUXFB = new ncpixelimpl_e("NCPIXEL_LINUXFB");
  public final static ncpixelimpl_e NCPIXEL_ITERM2 = new ncpixelimpl_e("NCPIXEL_ITERM2");
  public final static ncpixelimpl_e NCPIXEL_KITTY_STATIC = new ncpixelimpl_e("NCPIXEL_KITTY_STATIC");
  public final static ncpixelimpl_e NCPIXEL_KITTY_ANIMATED = new ncpixelimpl_e("NCPIXEL_KITTY_ANIMATED");
  public final static ncpixelimpl_e NCPIXEL_KITTY_SELFREF = new ncpixelimpl_e("NCPIXEL_KITTY_SELFREF");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ncpixelimpl_e swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ncpixelimpl_e.class + " with value " + swigValue);
  }

  private ncpixelimpl_e(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ncpixelimpl_e(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ncpixelimpl_e(String swigName, ncpixelimpl_e swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ncpixelimpl_e[] swigValues = { NCPIXEL_NONE, NCPIXEL_SIXEL, NCPIXEL_LINUXFB, NCPIXEL_ITERM2, NCPIXEL_KITTY_STATIC, NCPIXEL_KITTY_ANIMATED, NCPIXEL_KITTY_SELFREF };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

