/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.dundalek.notcurses.swig;

public class ncplane_options {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ncplane_options(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ncplane_options obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NCJNI.delete_ncplane_options(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setY(int value) {
    NCJNI.ncplane_options_y_set(swigCPtr, this, value);
  }

  public int getY() {
    return NCJNI.ncplane_options_y_get(swigCPtr, this);
  }

  public void setX(int value) {
    NCJNI.ncplane_options_x_set(swigCPtr, this, value);
  }

  public int getX() {
    return NCJNI.ncplane_options_x_get(swigCPtr, this);
  }

  public void setRows(long value) {
    NCJNI.ncplane_options_rows_set(swigCPtr, this, value);
  }

  public long getRows() {
    return NCJNI.ncplane_options_rows_get(swigCPtr, this);
  }

  public void setCols(long value) {
    NCJNI.ncplane_options_cols_set(swigCPtr, this, value);
  }

  public long getCols() {
    return NCJNI.ncplane_options_cols_get(swigCPtr, this);
  }

  public void setUserptr(SWIGTYPE_p_void value) {
    NCJNI.ncplane_options_userptr_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getUserptr() {
    long cPtr = NCJNI.ncplane_options_userptr_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setName(String value) {
    NCJNI.ncplane_options_name_set(swigCPtr, this, value);
  }

  public String getName() {
    return NCJNI.ncplane_options_name_get(swigCPtr, this);
  }

  public void setResizecb(SWIGTYPE_p_f_p_struct_ncplane__int value) {
    NCJNI.ncplane_options_resizecb_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_ncplane__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_ncplane__int getResizecb() {
    long cPtr = NCJNI.ncplane_options_resizecb_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_ncplane__int(cPtr, false);
  }

  public void setFlags(long value) {
    NCJNI.ncplane_options_flags_set(swigCPtr, this, value);
  }

  public long getFlags() {
    return NCJNI.ncplane_options_flags_get(swigCPtr, this);
  }

  public void setMargin_b(long value) {
    NCJNI.ncplane_options_margin_b_set(swigCPtr, this, value);
  }

  public long getMargin_b() {
    return NCJNI.ncplane_options_margin_b_get(swigCPtr, this);
  }

  public void setMargin_r(long value) {
    NCJNI.ncplane_options_margin_r_set(swigCPtr, this, value);
  }

  public long getMargin_r() {
    return NCJNI.ncplane_options_margin_r_get(swigCPtr, this);
  }

  public ncplane_options() {
    this(NCJNI.new_ncplane_options(), true);
  }

}
