/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.dundalek.notcurses.swig;

public class ncplot_options {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ncplot_options(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ncplot_options obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NCJNI.delete_ncplot_options(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setMaxchannels(long value) {
    NCJNI.ncplot_options_maxchannels_set(swigCPtr, this, value);
  }

  public long getMaxchannels() {
    return NCJNI.ncplot_options_maxchannels_get(swigCPtr, this);
  }

  public void setMinchannels(long value) {
    NCJNI.ncplot_options_minchannels_set(swigCPtr, this, value);
  }

  public long getMinchannels() {
    return NCJNI.ncplot_options_minchannels_get(swigCPtr, this);
  }

  public void setLegendstyle(int value) {
    NCJNI.ncplot_options_legendstyle_set(swigCPtr, this, value);
  }

  public int getLegendstyle() {
    return NCJNI.ncplot_options_legendstyle_get(swigCPtr, this);
  }

  public void setGridtype(ncblitter_e value) {
    NCJNI.ncplot_options_gridtype_set(swigCPtr, this, value.swigValue());
  }

  public ncblitter_e getGridtype() {
    return ncblitter_e.swigToEnum(NCJNI.ncplot_options_gridtype_get(swigCPtr, this));
  }

  public void setRangex(int value) {
    NCJNI.ncplot_options_rangex_set(swigCPtr, this, value);
  }

  public int getRangex() {
    return NCJNI.ncplot_options_rangex_get(swigCPtr, this);
  }

  public void setTitle(String value) {
    NCJNI.ncplot_options_title_set(swigCPtr, this, value);
  }

  public String getTitle() {
    return NCJNI.ncplot_options_title_get(swigCPtr, this);
  }

  public void setFlags(long value) {
    NCJNI.ncplot_options_flags_set(swigCPtr, this, value);
  }

  public long getFlags() {
    return NCJNI.ncplot_options_flags_get(swigCPtr, this);
  }

  public ncplot_options() {
    this(NCJNI.new_ncplot_options(), true);
  }

}
