/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.dundalek.notcurses.swig;

public class ncprogbar_options {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ncprogbar_options(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ncprogbar_options obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NCJNI.delete_ncprogbar_options(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setUlchannel(long value) {
    NCJNI.ncprogbar_options_ulchannel_set(swigCPtr, this, value);
  }

  public long getUlchannel() {
    return NCJNI.ncprogbar_options_ulchannel_get(swigCPtr, this);
  }

  public void setUrchannel(long value) {
    NCJNI.ncprogbar_options_urchannel_set(swigCPtr, this, value);
  }

  public long getUrchannel() {
    return NCJNI.ncprogbar_options_urchannel_get(swigCPtr, this);
  }

  public void setBlchannel(long value) {
    NCJNI.ncprogbar_options_blchannel_set(swigCPtr, this, value);
  }

  public long getBlchannel() {
    return NCJNI.ncprogbar_options_blchannel_get(swigCPtr, this);
  }

  public void setBrchannel(long value) {
    NCJNI.ncprogbar_options_brchannel_set(swigCPtr, this, value);
  }

  public long getBrchannel() {
    return NCJNI.ncprogbar_options_brchannel_get(swigCPtr, this);
  }

  public void setFlags(long value) {
    NCJNI.ncprogbar_options_flags_set(swigCPtr, this, value);
  }

  public long getFlags() {
    return NCJNI.ncprogbar_options_flags_get(swigCPtr, this);
  }

  public ncprogbar_options() {
    this(NCJNI.new_ncprogbar_options(), true);
  }

}
