/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.dundalek.notcurses.swig;

public class ncreel_options {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ncreel_options(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ncreel_options obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NCJNI.delete_ncreel_options(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setBordermask(long value) {
    NCJNI.ncreel_options_bordermask_set(swigCPtr, this, value);
  }

  public long getBordermask() {
    return NCJNI.ncreel_options_bordermask_get(swigCPtr, this);
  }

  public void setBorderchan(long value) {
    NCJNI.ncreel_options_borderchan_set(swigCPtr, this, value);
  }

  public long getBorderchan() {
    return NCJNI.ncreel_options_borderchan_get(swigCPtr, this);
  }

  public void setTabletmask(long value) {
    NCJNI.ncreel_options_tabletmask_set(swigCPtr, this, value);
  }

  public long getTabletmask() {
    return NCJNI.ncreel_options_tabletmask_get(swigCPtr, this);
  }

  public void setTabletchan(long value) {
    NCJNI.ncreel_options_tabletchan_set(swigCPtr, this, value);
  }

  public long getTabletchan() {
    return NCJNI.ncreel_options_tabletchan_get(swigCPtr, this);
  }

  public void setFocusedchan(long value) {
    NCJNI.ncreel_options_focusedchan_set(swigCPtr, this, value);
  }

  public long getFocusedchan() {
    return NCJNI.ncreel_options_focusedchan_get(swigCPtr, this);
  }

  public void setFlags(long value) {
    NCJNI.ncreel_options_flags_set(swigCPtr, this, value);
  }

  public long getFlags() {
    return NCJNI.ncreel_options_flags_get(swigCPtr, this);
  }

  public ncreel_options() {
    this(NCJNI.new_ncreel_options(), true);
  }

}
