/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.dundalek.notcurses.swig;

public class ncreader_options {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ncreader_options(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ncreader_options obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NCJNI.delete_ncreader_options(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTchannels(long value) {
    NCJNI.ncreader_options_tchannels_set(swigCPtr, this, value);
  }

  public long getTchannels() {
    return NCJNI.ncreader_options_tchannels_get(swigCPtr, this);
  }

  public void setTattrword(long value) {
    NCJNI.ncreader_options_tattrword_set(swigCPtr, this, value);
  }

  public long getTattrword() {
    return NCJNI.ncreader_options_tattrword_get(swigCPtr, this);
  }

  public void setFlags(long value) {
    NCJNI.ncreader_options_flags_set(swigCPtr, this, value);
  }

  public long getFlags() {
    return NCJNI.ncreader_options_flags_get(swigCPtr, this);
  }

  public ncreader_options() {
    this(NCJNI.new_ncreader_options(), true);
  }

}
