/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.dundalek.notcurses.swig;

public final class ncscale_e {
  public final static ncscale_e NCSCALE_NONE = new ncscale_e("NCSCALE_NONE");
  public final static ncscale_e NCSCALE_SCALE = new ncscale_e("NCSCALE_SCALE");
  public final static ncscale_e NCSCALE_STRETCH = new ncscale_e("NCSCALE_STRETCH");
  public final static ncscale_e NCSCALE_NONE_HIRES = new ncscale_e("NCSCALE_NONE_HIRES");
  public final static ncscale_e NCSCALE_SCALE_HIRES = new ncscale_e("NCSCALE_SCALE_HIRES");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ncscale_e swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ncscale_e.class + " with value " + swigValue);
  }

  private ncscale_e(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ncscale_e(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ncscale_e(String swigName, ncscale_e swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ncscale_e[] swigValues = { NCSCALE_NONE, NCSCALE_SCALE, NCSCALE_STRETCH, NCSCALE_NONE_HIRES, NCSCALE_SCALE_HIRES };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

