/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.dundalek.notcurses.swig;

public class ncsubproc_options {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ncsubproc_options(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ncsubproc_options obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NCJNI.delete_ncsubproc_options(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCurry(SWIGTYPE_p_void value) {
    NCJNI.ncsubproc_options_curry_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getCurry() {
    long cPtr = NCJNI.ncsubproc_options_curry_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setRestart_period(long value) {
    NCJNI.ncsubproc_options_restart_period_set(swigCPtr, this, value);
  }

  public long getRestart_period() {
    return NCJNI.ncsubproc_options_restart_period_get(swigCPtr, this);
  }

  public void setFlags(long value) {
    NCJNI.ncsubproc_options_flags_set(swigCPtr, this, value);
  }

  public long getFlags() {
    return NCJNI.ncsubproc_options_flags_get(swigCPtr, this);
  }

  public ncsubproc_options() {
    this(NCJNI.new_ncsubproc_options(), true);
  }

}
