/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.dundalek.notcurses.swig;

public class nctabbed_options {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected nctabbed_options(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(nctabbed_options obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NCJNI.delete_nctabbed_options(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setSelchan(long value) {
    NCJNI.nctabbed_options_selchan_set(swigCPtr, this, value);
  }

  public long getSelchan() {
    return NCJNI.nctabbed_options_selchan_get(swigCPtr, this);
  }

  public void setHdrchan(long value) {
    NCJNI.nctabbed_options_hdrchan_set(swigCPtr, this, value);
  }

  public long getHdrchan() {
    return NCJNI.nctabbed_options_hdrchan_get(swigCPtr, this);
  }

  public void setSepchan(long value) {
    NCJNI.nctabbed_options_sepchan_set(swigCPtr, this, value);
  }

  public long getSepchan() {
    return NCJNI.nctabbed_options_sepchan_get(swigCPtr, this);
  }

  public void setSeparator(String value) {
    NCJNI.nctabbed_options_separator_set(swigCPtr, this, value);
  }

  public String getSeparator() {
    return NCJNI.nctabbed_options_separator_get(swigCPtr, this);
  }

  public void setFlags(long value) {
    NCJNI.nctabbed_options_flags_set(swigCPtr, this, value);
  }

  public long getFlags() {
    return NCJNI.nctabbed_options_flags_get(swigCPtr, this);
  }

  public nctabbed_options() {
    this(NCJNI.new_nctabbed_options(), true);
  }

}
