/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.dundalek.notcurses.swig;

public class nctree_item {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected nctree_item(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(nctree_item obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NCJNI.delete_nctree_item(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setCurry(SWIGTYPE_p_void value) {
    NCJNI.nctree_item_curry_set(swigCPtr, this, SWIGTYPE_p_void.getCPtr(value));
  }

  public SWIGTYPE_p_void getCurry() {
    long cPtr = NCJNI.nctree_item_curry_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public void setSubs(nctree_item value) {
    NCJNI.nctree_item_subs_set(swigCPtr, this, nctree_item.getCPtr(value), value);
  }

  public nctree_item getSubs() {
    long cPtr = NCJNI.nctree_item_subs_get(swigCPtr, this);
    return (cPtr == 0) ? null : new nctree_item(cPtr, false);
  }

  public void setSubcount(long value) {
    NCJNI.nctree_item_subcount_set(swigCPtr, this, value);
  }

  public long getSubcount() {
    return NCJNI.nctree_item_subcount_get(swigCPtr, this);
  }

  public nctree_item() {
    this(NCJNI.new_nctree_item(), true);
  }

}
