/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.dundalek.notcurses.swig;

public class nctree_options {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected nctree_options(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(nctree_options obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NCJNI.delete_nctree_options(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setItems(nctree_item value) {
    NCJNI.nctree_options_items_set(swigCPtr, this, nctree_item.getCPtr(value), value);
  }

  public nctree_item getItems() {
    long cPtr = NCJNI.nctree_options_items_get(swigCPtr, this);
    return (cPtr == 0) ? null : new nctree_item(cPtr, false);
  }

  public void setCount(long value) {
    NCJNI.nctree_options_count_set(swigCPtr, this, value);
  }

  public long getCount() {
    return NCJNI.nctree_options_count_get(swigCPtr, this);
  }

  public void setNctreecb(SWIGTYPE_p_f_p_struct_ncplane_p_void_int__int value) {
    NCJNI.nctree_options_nctreecb_set(swigCPtr, this, SWIGTYPE_p_f_p_struct_ncplane_p_void_int__int.getCPtr(value));
  }

  public SWIGTYPE_p_f_p_struct_ncplane_p_void_int__int getNctreecb() {
    long cPtr = NCJNI.nctree_options_nctreecb_get(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_f_p_struct_ncplane_p_void_int__int(cPtr, false);
  }

  public void setIndentcols(int value) {
    NCJNI.nctree_options_indentcols_set(swigCPtr, this, value);
  }

  public int getIndentcols() {
    return NCJNI.nctree_options_indentcols_get(swigCPtr, this);
  }

  public void setFlags(long value) {
    NCJNI.nctree_options_flags_set(swigCPtr, this, value);
  }

  public long getFlags() {
    return NCJNI.nctree_options_flags_get(swigCPtr, this);
  }

  public nctree_options() {
    this(NCJNI.new_nctree_options(), true);
  }

}
