/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.dundalek.notcurses.swig;

public class notcurses_options {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected notcurses_options(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(notcurses_options obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        NCJNI.delete_notcurses_options(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setTermtype(String value) {
    NCJNI.notcurses_options_termtype_set(swigCPtr, this, value);
  }

  public String getTermtype() {
    return NCJNI.notcurses_options_termtype_get(swigCPtr, this);
  }

  public void setLoglevel(ncloglevel_e value) {
    NCJNI.notcurses_options_loglevel_set(swigCPtr, this, value.swigValue());
  }

  public ncloglevel_e getLoglevel() {
    return ncloglevel_e.swigToEnum(NCJNI.notcurses_options_loglevel_get(swigCPtr, this));
  }

  public void setMargin_t(long value) {
    NCJNI.notcurses_options_margin_t_set(swigCPtr, this, value);
  }

  public long getMargin_t() {
    return NCJNI.notcurses_options_margin_t_get(swigCPtr, this);
  }

  public void setMargin_r(long value) {
    NCJNI.notcurses_options_margin_r_set(swigCPtr, this, value);
  }

  public long getMargin_r() {
    return NCJNI.notcurses_options_margin_r_get(swigCPtr, this);
  }

  public void setMargin_b(long value) {
    NCJNI.notcurses_options_margin_b_set(swigCPtr, this, value);
  }

  public long getMargin_b() {
    return NCJNI.notcurses_options_margin_b_get(swigCPtr, this);
  }

  public void setMargin_l(long value) {
    NCJNI.notcurses_options_margin_l_set(swigCPtr, this, value);
  }

  public long getMargin_l() {
    return NCJNI.notcurses_options_margin_l_get(swigCPtr, this);
  }

  public void setFlags(long value) {
    NCJNI.notcurses_options_flags_set(swigCPtr, this, value);
  }

  public long getFlags() {
    return NCJNI.notcurses_options_flags_get(swigCPtr, this);
  }

  public notcurses_options() {
    this(NCJNI.new_notcurses_options(), true);
  }

}
